import 'package:mandaos/generated/assets.dart';
import 'package:mandaos/models/product.dart';

import 'database_helper.dart';






final List<Product> list_products = [
  Product(
      id: 1,
      title: 'Arroz consumo nacional',
      price: 6,
      cuota: 7,
      um: 'lbs',
      img: Assets.imgCubaarroz, recomended: 1,
      kid: 0,

  ),

  Product(
      id: 2,
      title: 'Arroz Importado (con 15% de partidura)',
      price: 7,
      cuota: 7,
      um: 'lbs',
      img: 'assets/img/arrozImportado.jpg', recomended: 0,kid: 0,),
  Product(
      id: 3,
      title: 'Arroz Importado (con 4% de partidura)',
      price: 10,
      cuota: 7,
      um: 'lbs',
      img: Assets.imgArrozNacional, recomended: 0,kid: 0,),
  Product(
      id: 4,
      title: 'Frijoles Negros nacionales',
      price: 0.875,
      cuota: 14,
      um: 'oz',
      img: 'assets/img/frijolNegro.jpg', recomended: 0,kid: 0,),
  Product(
      id: 5,
      title: 'Frijoles Importados',
      price: 16,
      cuota: 10,
      um: 'oz',
      img: Assets.imgFrijolesCol, recomended: 0,kid: 0,),
  Product(
      id: 6,
      title: 'Frijoles Colorados nacionales',
      price: 1,
      cuota: 10,
      um: 'oz',
      img: Assets.imgFrijolesColorados2, recomended: 0,kid: 0,),
  Product(
      id: 7,
      title: 'Chicharo',
      price: 0.3125,
      cuota: 10,
      um: 'oz',
      img: 'assets/img/chicharos.jpg', recomended: 0,kid: 0,),
  Product(
      id: 8,
      title: 'Aceite vegetal a granel',
      price: 12,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/aceiteCocinerito.jpg', recomended: 0,kid: 0,),
  Product(
      id: 9,
      title: 'Aceite vegetal de soya',
      price: 18,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/aceite.jpg', recomended: 1,kid: 0,),
  Product(
      id: 10,
      title: 'Azúcar Blanca',
      price: 6,
      cuota: 3,
      um: 'lbs',
      img: 'assets/img/azucarBlanca.jpg', recomended: 1,kid: 0,),
  Product(
      id: 11,
      title: 'Azúcar Prieta',
      price: 5,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/azucarPrieta.jpg', recomended: 1,kid: 0,),
  Product(
      id: 12,
      title: 'Café mezclado',
      price: 2,
      cuota: 4,
      um: 'oz',
      img: 'assets/img/cafeHola.jpg', recomended: 0,kid: 0,),
  Product(
      id: 13,
      title: 'Sal común',
      price: 7,
      cuota: 1,
      um: 'kg',
      img: 'assets/img/sal.jpg', recomended: 0,kid: 0,),
  Product(
      id: 14,
      title: 'Pastas Alimenticias',
      price: 15,
      cuota: 0.88,
      um: 'paquete (400g)',
      img: 'assets/img/spaguetis.png', recomended: 0,kid: 0,),
  Product(
      id: 15,
      title: 'Leche en polvo entera (normada y dieta médica)',
      price: 2.5,
      cuota: 1,
      um: 'kg',
      img: 'assets/img/lecheEntera.jpg', recomended: 0,kid: 0,),
  Product(
      id: 16,
      title: 'Leche en polvo descremada (dieta médica)',
      price: 2.5,
      cuota: 1,
      um: 'kg',
      img: 'assets/img/lecheDescremeda.png', recomended: 0,kid: 0,),
  Product(
      id: 17,
      title: 'Yogurt de Soya',
      price: 5,
      cuota: 1,
      um: 'bolsa',
      img: 'assets/img/yogurSoya.jpg', recomended: 0,kid: 0,),
  Product(
      id: 18,
      title: 'Lactosoy en bolsas de 1 Kg',
      price: 25,
      cuota: 1,
      um: 'kg',
      img: 'assets/img/lactosoy.png', recomended: 0,kid: 0,),
  Product(
      id: 19,
      title: 'Picadillo de Res (niños)',
      price: 0.70,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/picadilloRes.jpg', recomended: 0,kid: 1,),
  Product(
      id: 20,
      title: 'Pollo de niño',
      price: 0.70,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/polloKid.png', recomended: 0,kid: 1,),
  Product(
      id: 21,
      title: 'Pollo de población',
      price: 20,
      cuota: 1.75,
      um: 'lbs',
      img: 'assets/img/pollo.jpg', recomended: 1,kid: 0,),
  Product(
      id: 22,
      title: 'Picadillo Texturizado',
      price: 0.70,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/picadilloSoya.jpg', recomended: 0,kid: 0,),
  Product(
      id: 23,
      title: 'Pescado de Dieta',
      price: 19,
      cuota: 1,
      um: 'lbs',
      img: 'assets/img/pescado.jpg', recomended: 0,kid: 0,),
  Product(
      id: 24,
      title: 'Huevos',
      price: 2.20,
      cuota: 10,
      um: 'uno',
      img: 'assets/img/cartonHuevos.jpg', recomended: 1, kid: 0,),
    Product(
        id: 24,
        title: 'Mortadella o jamonada',
        price: 17,
        cuota: 0.5,
        um: 'lbs',
        img: Assets.imgJamonada, recomended: 0, kid: 0,),
    Product(
        id: 24,
        title: 'Compota normada',
        price: 0.30,
        cuota: 13,
        um: 'uno',
        img: Assets.imgCompota, recomended: 0, kid: 1,),
    Product(
        id: 25,
        title: 'Pan normado',
        price: 1,
        cuota: 1,
        um: 'uno',
        img: Assets.imgPan, recomended: 0, kid: 0,),
    Product(
        id: 26,
        title: 'Jabón Tocador Lis',
        price: 5,
        cuota: 1,
        um: 'uno',
        img: Assets.imgJabonLis, recomended: 0, kid: 0,),
    Product(
        id: 27,
        title: 'Jabón Tocador Daily',
        price: 7,
        cuota: 1,
        um: 'uno',
        img: Assets.imgDayli, recomended: 0, kid: 0,),
    Product(
        id: 28,
        title: 'Jabón Tocador Nacar',
        price: 7,
        cuota: 1,
        um: 'uno',
        img: Assets.imgJabontnacar, recomended: 0, kid: 0,),
    Product(
        id: 29,
        title: 'Jabón de lavar',
        price: 6,
        cuota: 1,
        um: 'uno',
        img: Assets.imgNacar2, recomended: 0, kid: 0,),
    Product(
        id: 29,
        title: 'Pasta Dental',
        price: 8,
        cuota: 1,
        um: 'uno',
        img: Assets.imgPasta, recomended: 0, kid: 0,),
    Product(
        id: 29,
        title: 'Detergente Líquido',
        price: 25,
        cuota: 1,
        um: 'uno',
        img: Assets.imgDetergente2, recomended: 0, kid: 0,),
];
